# Generated by Django 3.0.5 on 2020-10-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSchedule',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='locations.OrgLocation')),
                ('sunday', models.CharField(max_length=30)),
                ('monday', models.CharField(max_length=30)),
                ('tuesday', models.CharField(max_length=30)),
                ('wednesday', models.CharField(max_length=30)),
                ('thursday', models.CharField(max_length=30)),
                ('friday', models.CharField(max_length=30)),
                ('saturday', models.CharField(max_length=30)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
