# Generated by Django 3.0.5 on 2020-11-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgschedule',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='locations.OrgLocationLL'),
        ),
    ]
