# Generated by Django 3.0.5 on 2020-11-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20201113_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='tags',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
