# Generated by Django 3.0.5 on 2020-11-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_locationreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreviews',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='locations.OrgLocationLL'),
        ),
    ]
