export const GET_LOCATIONS = "GET_LOCATIONS";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const GET_SCHEDULES = "GET_SCHEDULES";
export const GET_LOCATIONSLL = "GET_LOCATIONSLL";

export const ADD_U_LOCATION  = "ADD_U_LOCATION";
export const GET_U_LOCATIONS  = "GET_U_LOCATIONS";
export const DELETE_U_LOCATION = "DELETE_U_LOCATION";
export const EDIT_U_LOCATION  = "EDIT_U_LOCATION";

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";

export const ADD_L_REVIEW  = "ADD_L_REVIEW";
export const GET_L_REVIEW  = "GET_L_REVIEW";

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';